# Generated by Django 3.2.8 on 2021-10-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Seed', 'Seed'), ('Plant', 'Plant')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('Rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Not Bad'), (3, 'Average'), (4, 'Nice'), (5, 'Excellent')], default=3)),
                ('light', models.CharField(max_length=32)),
                ('watering', models.CharField(max_length=32)),
                ('time_till_harvest', models.CharField(max_length=32)),
                ('where_to_grow', models.CharField(max_length=32)),
                ('seasonal_information', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.categoryseed')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contactNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backendAPI.categoryseed')),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.seeditem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.seller')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='seeds',
            field=models.ManyToManyField(through='backendAPI.Sold', to='backendAPI.SeedItem'),
        ),
        migrations.AddField(
            model_name='seeditem',
            name='sellers',
            field=models.ManyToManyField(through='backendAPI.Sold', to='backendAPI.Seller'),
        ),
        migrations.AddField(
            model_name='seeditem',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.subcategory'),
        ),
        migrations.AddField(
            model_name='categoryseed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.product'),
        ),
    ]
