# Generated by Django 3.2.8 on 2021-10-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backendAPI.categoryseed'),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backendAPI.subcategory'),
        ),
    ]
