# Generated by Django 3.2.8 on 2021-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0003_seeditem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='info',
            field=models.CharField(max_length=500),
        ),
    ]
