# Generated by Django 3.2.8 on 2021-10-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_alter_seeditem_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='sub_category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='backendAPI.subcategory'),
        ),
    ]
