# Generated by Django 3.2.8 on 2021-10-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0006_alter_seeditem_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryseed',
            old_name='category',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='category',
        ),
    ]
