# Generated by Django 3.2.8 on 2021-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0008_alter_seeditem_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='light',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='time_till_harvest',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='watering',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='where_to_grow',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
