# Generated by Django 3.2.8 on 2021-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0009_auto_20211022_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='seasonal_information',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
