# Generated by Django 3.2.6 on 2021-10-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0010_alter_seeditem_seasonal_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeditem',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='backendAPI.categoryseed'),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='sellers',
            field=models.ManyToManyField(related_name='seller', through='backendAPI.Sold', to='backendAPI.Seller'),
        ),
        migrations.AlterField(
            model_name='seeditem',
            name='sub_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='backendAPI.subcategory'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='seed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='backendAPI.seeditem'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='backendAPI.seller'),
        ),
    ]
